### ISSUE TITLE
[report draft] panic on cloud ver garoon login

### ISSUE THREAD

**Issue by nukosuke** [nukosuke/goroon#1]
```
./cmd l -u [username] -p [password] -e "https://xxxxxx.cybozu.com/g/"
panic: runtime error: index out of range

goroutine 1 [running]:
main.main.func2(0xc4200e83c0, 0x10100, 0xc4200e83c0)
        /Users/nukosuke/.gvm/pkgsets/go1.10/global/src/github.com/tzmfreedom/goroon/cmd/main.go:97 +0x2e9
github.com/tzmfreedom/goroon/vendor/github.com/urfave/cli.HandleAction(0x133ad80, 0xc420062c90, 0xc4200e83c0, 0xc42008c100, 0x0)
        /Users/nukosuke/.gvm/pkgsets/go1.10/global/src/github.com/tzmfreedom/goroon/vendor/github.com/urfave/cli/app.go:485 +0xc8
github.com/tzmfreedom/goroon/vendor/github.com/urfave/cli.Command.Run(0x13b034c, 0x5, 0x0, 0x0, 0xc420062cc0, 0x1, 0x1, 0x13b2eed, 0xf, 0x0, ...)
        /Users/nukosuke/.gvm/pkgsets/go1.10/global/src/github.com/tzmfreedom/goroon/vendor/github.com/urfave/cli/command.go:193 +0xa35
github.com/tzmfreedom/goroon/vendor/github.com/urfave/cli.(*App).Run(0xc4200a29c0, 0xc420010080, 0x8, 0x8, 0x0, 0x0)
        /Users/nukosuke/.gvm/pkgsets/go1.10/global/src/github.com/tzmfreedom/goroon/vendor/github.com/urfave/cli/app.go:250 +0x700
main.main()
        /Users/nukosuke/.gvm/pkgsets/go1.10/global/src/github.com/tzmfreedom/goroon/cmd/main.go:286 +0x131f
```

```go
// L92~L96: in Login Action
				r := regexp.MustCompile(`CBSESSID=(.+?);`)
				group := r.FindAllStringSubmatch(res.Cookie, -1)
				createConfigFile(group[0][1], c.Endpoint)
				return err
			},
```

`fmt.Println()` `res.Cookie` and `group` before `return err`.

**output**

```
JSESSIONID=xxxxxxxxxxxxxxxxxxxx; path=/
[]
```

`CBSESSID` is not found.

According to [API document](https://developer.cybozu.io/hc/ja/articles/202228464-Garoon-SOAP-API%E3%81%AE%E5%85%B1%E9%80%9A%E4%BB%95%E6%A7%98).

| 製品 | Cookie名 |
|:--|:--|
| クラウド版 Garoon | JSESSIONID |
| パッケージ版 Garoon バージョン3.0.0以降 | CBSESSID |

It's necessary to switch session key according to version.

**Comment by nukosuke** [comment]
fork元にあげたのでclose
